---
title: " "
output: pdf_document
bibliography: bibliography.bib
biblio-style: apalike
header-includes:
  - \usepackage{float}
  - \usepackage{sectsty}
---

# 1.0 Introduction

  Worldwide, forests are vital carbon sinks and they store carbon belowground and aboveground. The boreal forest is the largest forest biome in the world and more than 20% of this zone is in Canada contributing to 8% of the world’s forests [@brandt2009extent]. Canada’s boreal forests accumulate over 28 Pg of Carbon [@kurz2013carbon] making them important global C reservoirs. A vast amount of Carbon has accumulated within this zone because of slow decomposition from cold temperatures and from their anoxic conditions [@kurz2013carbon].

Although this zone has been known for a very long time to be a C sink, drier air temperatures attributed to climate change are now making them vulnerable to wildfire by enhancing drier fuels below and aboveground. Wildfire is currently the dominant disturbance impacting the boreal forest and accounting for vast amounts of C [@potter2023burned]. Carbon loss is the release of particles, gases, and aerosols into the atmosphere. Wulder et al. (2020) estimated that about 1.79 Pg of biomass had been lost as a result of fire disturbance from 1985–2016. In addition to this, fire regimes are also changing, and these trends are projected to increase as climate change progresses. Changes to fire regimes in Canada include an increase in area burned, fire intensity, and fire severity leading to more carbon emission from fires both aboveground and belowground. For example, over 17 Mha have burned just from the fires in 2023 alone in Canada. This is 5 times higher than the 2.37 Mha annual burn reported by Potter et al. (2023) in the past two decades. Changes in Canada’s fire regime (fire frequency, intensity, burned area, fire severity) have the ability to convert some of these forest biomass C stocks to carbon sources, and this ecosystem might not return to its original biomass carbon storage.

To understand the impact of fires on Canada’s boreal forest where small fluctuations in temperature are already noted and projected to have a significant effect on climate change, there is a critical need to estimate and understand the carbon loss from fire. This will not only help to improve carbon modeling and reporting but also provide mitigation measures for the areas where these trends are expected to be high.

There are two approaches to estimating carbon loss from fires. The first is the more traditional approach where the area burned, the fuel load (biomass consumed), the combustion completeness, and the fraction of carbon are taken into account [@french2011model]. The second approach is the remotely sensed method where statistical techniques are used to model combustion by establishing a relationship between field combustion and remotely sensed variables. For the more traditional approach of C emissions, a lot of uncertainties arise when accounting for fuel load and combustion completeness as it differs from landscape to landscape [@hookcarbon; @rogers2014quantifying]. The latter is now used widely because of the availability of satellite imagery and the integration of field C measurements. Fuel load can be mapped with remote-sensed observations, and C loss information can cover a larger extent both spatially and temporally. Typically, remote sensing estimates of C loss rely on a statistical approach between field measurements of C loss and absorption properties from either active or passive sensors. Several studies have found a significant relationship between remote sensing observation and carbon combustion across the boreal forests [@veraverbeke2015daily]. The difference normalized burn ratio along with other environmental spectral inputs, topographic, and climate variables are derived to explain C loss. For example, Rogers et al. (2014) was able to estimate the amount of below and aboveground carbon loss from fire disturbance in Alaska using dNBR and field combustion. Veraverbeke et al. (2015) using geospatial data and environmental variables reported that elevation, the day of burning, burn severity (dNBR), and tree cover were the drivers of carbon emission from boreal fires in Alaska. Similarly, Potter et al. (2023) related fire combustion measurements with predictor variables of climate, fire weather indices, environmental variables, and remotely sensed variables. He reported that the period where a larger fire year was witnessed and later season burning generally accounted for a higher mean combustion. Tree cover, relative humidity, Normalized Difference Infrared Index (NDII), and dNBR were the most important variables for aboveground combustion, while silt, slope, solar radiation, tree cover, and sand were the drivers of combustion for belowground combustion.

Carbon emission mapping, such as our studies here, will allow for improving C emission accounting, modeling, and reporting and also more accurate prediction of C losses, which is a very key importance discussion within the United Nations framework accounting.

Most of the research modeling carbon emission from disturbances such as wildfire only looked at Alaska and sometimes a combination of Alaska and western Canada. This research will be the first to provide belowground, soil, and aboveground C emissions for the entire Canada. Here, we are looking at the carbon emission from fire for the entire Canada considering that this year, Canada had the worst fire seasons compared to other years. It is, therefore, important to understand the C that has been released from this disturbance and mitigation measures that can be carried out to help this ecosystem recover from this disturbance. And also, carbon emission modeling of Canada will help in improving Canada's C loss emission report and modeling and also to understand the drivers of C emission within Canada’s forest.

## 1.1 Research Aim & Objectives
The primary goal of this study is to estimate the amount of carbon loss from wildfire disturbance within Canada’s forests. The specific objectives include:




